name: Checks

on:
  workflow_run:
    workflows:
      - autofix.ci
    types:
      - completed
    branches:
      - main
      - dev

jobs:
  lint-typecheck:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Lint and Typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Checks
        run: pnpm run ci
