name: Pull Request CI

on: [pull_request]

jobs:
  lint-typecheck:
    name: Lint and Typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Checks
        run: pnpm run ci
